apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-consumer-l-trip-update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-consumer
      feed: l
      type: trip-update
  template:
    metadata:
      labels:
        app: redis-consumer
        feed: l
        type: trip-update
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: consumer
          image: johnmccormick7/mta-gtfs-pipeline:gtfs-redis-consumer-latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_TOPICS
              value: "feed-l-trip-update"
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: brokers
            - name: REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: redis-config       
                  key:  redis_addr         
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis          
                  key:  redis-password
