apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigquery-consumer-bdfm-vehicle-position
  labels:
    app: bigquery-consumer-bdfm-vehicle-position
spec:
  replicas: 3 # You can scale this later
  selector:
    matchLabels:
      app: bigquery-consumer-bdfm-vehicle-position
  template:
    metadata:
      labels:
        app: bigquery-consumer-bdfm-vehicle-position
    spec:
      serviceAccountName: bigquery-consumer-ksa
      nodeSelector:
        kubernetes.io/arch: amd64
      containers:
        - name: consumer
          image: johnmccormick7/mta-gtfs-pipeline:bigquery-consumer-latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: brokers
            - name: KAFKA_FEEDS
              value: "feed-bdfm-vehicle-position"
            - name: BQ_DATASET_ID
              value: "mta-realtime-pipeline.mta_realtime_data"
