apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-consumer-nrqw-trip-update
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-consumer
      feed: nrqw
      type: trip-update
  template:
    metadata:
      labels:
        app: redis-consumer
        feed: nrqw
        type: trip-update
    spec:
      containers:
        - name: consumer
          image: johnmccormick7/mta-gtfs-pipeline:gtfs-redis-consumer-latest
          env:
            - name: KAFKA_TOPICS
              value: "feed-nrqw-trip-update"
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: brokers
            - name: REDIS_ADDR
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis_addr
