apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs-producer-ace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtfs-producer
      feed: ace
  template:
    metadata:
      labels:
        app: gtfs-producer
        feed: ace
    spec:
      containers:
        - name: producer
          image: johnmccormick7/mta-gtfs-pipeline:gtfs-producer-latest
          env:
            - name: FEED_URL
              value: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-ace"
            - name: KAFKA_TOPIC
              value: "feed-ace"
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: brokers
