apiVersion: apps/v1
kind: Deployment
metadata:
  name: gtfs-producer-nrqw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gtfs-producer
      feed: nrwq
  template:
    metadata:
      labels:
        app: gtfs-producer
        feed: nrqw
    spec:
      containers:
        - name: producer
          image: johnmccormick7/mta-gtfs-pipeline:gtfs-producer-latest
          env:
            - name: FEED_URL
              value: "https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-nqrw"
            - name: KAFKA_TOPIC
              value: "feed-nrqw"
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: brokers
