apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default # Optional: change if you're using another namespace
data:
  brokers: "kafka-controller-headless.default.svc.cluster.local:9094" # If running Kafka inside K8s (use service name)
